### ISSUE TITLE
Sparse Block 판단 어떻게??

### ISSUE THREAD

**Issue by taeguk** [PYO2016/PyoCore#1]
문제. Tessaract에서 표 테두리가 있을 경우 OCR 불가. (sparse block 얻어내기 불가능)

방안1. 표 테두리를 결정지은 다음 각 셀에 대해 OCR을 돌린다. (sparse block을 찾아낸다.)
- 잘못 판정된 표 테두리에 의해 끊켜진 sparse block을 다시 합쳐주는 과정이 추가적으로 필요하다. 이 과정을 하고나면 잘못 판정된 표 테두리는 제거된다.

다른 방안이나 의견 있으십니까?

**Comment by vyujing** [comment]
아무래도 저 방법이 가장 괜찮을 듯 하지만 테두리를 완벽하게 제거할 수 있을지가 확신이 안듬(테두리가 어느정도 있는 네모가 나올거라고 생각돼서...) 추후 테스트 필요할 것 같습니다.

**Comment by corvinox** [comment]
방안2. 전처리의 일환으로 테두리를 먼저 다 획득한 후에 각 부분에 대해서 OCR을 돌린다.

**Comment by taeguk** [comment]
우리가 직접 짜는걸로!! (아니면 라이브러리나 오픈소스 있나??)

**Comment by taeguk** [comment]
우리가 그냥 스파스블럭 찾는 알고리즘을 짰음.
OCR은 아마 결정된 Cell들에 대해서 돌릴듯?
