### ISSUE TITLE
Histogram::initExtremumFilter 코드 리뷰.

### ISSUE THREAD

**Issue by taeguk** [PYO2016/PyoCore#4]
광민이 형이 짜셨던 Histogram::initExtremumFilter의 코드를 리뷰해봤고, 그 결과 생각난 issue들을 정리해보았습니다.
1. 첫 극값을 선정하는 부분 (bug)
   https://github.com/PYO2016/PyoCore/blob/6c10a7d0aed47c4fbbc702ee51a9febbc189179a/PyoCore/TableDetection/HistogramManager.cpp#L127-L128
   histogram values가 9 9 9 6 ..... 일 경우, 지금 코드는 1번째 9가 극소가 되게 됩니다. 하지만 실제로는 3번째 9가 극대가 되야합니다.
2. 마지막 histogram value에 대한 극값 여부 판정 방법 (bug)
   https://github.com/PYO2016/PyoCore/blob/6c10a7d0aed47c4fbbc702ee51a9febbc189179a/PyoCore/TableDetection/HistogramManager.cpp#L147-L150
   histogram values가 ..... 5 3 5 9 9 9 일 경우,  지금 3만 극소가 됩니다. 하지만 실제로는 마지막 9도 극대로 판정되야합니다.
3. nextItr는 invalid할 수 있다. (bug)
   https://github.com/PYO2016/PyoCore/blob/6c10a7d0aed47c4fbbc702ee51a9febbc189179a/PyoCore/TableDetection/HistogramManager.cpp#L170
   179번째 줄에 의해 nextItr가 list의 end가 될 수 있고, 이경우 170줄에서 nextItr은 invalid합니다.
4. 불필요한 move operator= (enhancement)
   https://github.com/PYO2016/PyoCore/blob/6c10a7d0aed47c4fbbc702ee51a9febbc189179a/PyoCore/TableDetection/HistogramManager.cpp#L182
   182줄을 지우고 처음에 eList를 const auto &eList = this->extremeList; 하는게 성능상 좋을 것 같습니다.

위와 같은 issue들이 나왔는데 어떻게들 생각하시나용??
다른 분들도 동의하시면 patch를 작성하여 pull request를 보낼께요~

**Comment by vyujing** [comment]
오 ㅋㅋㅋㅋ 코드리뷰까지 하다니 대단하군 1번 3번은 어제 고쳤는데 커밋을 아직 안했어 2번이랑 4번은 생각도 못했네 ㅋㅋㅋ 고쳐야 할거같아 ㅋㅋ

**Comment by taeguk** [comment]
ㅋㅋㅋㅋㅋㅋ 코드리뷰 너무나 잼난 것

**Comment by vyujing** [comment]
홍ㅋㅋ 추가적으로 이슈는 k-means를 돌렸을 때 클러스터가 하나밖에 나오지 않을때는 divide by zero가 일어나서 뻗어버리는데 이거에 대해서도 클러스터링이 예상대로 진행돠지 못하면 에러코드를 리턴하는 식으로 getBoundary함수를 바꿔야 할듯 ㅋㅋ -> 내일밤이나 모레 ㅠ

**Comment by taeguk** [comment]
그 부분은 https://github.com/PYO2016/PyoCore/issues/5 여기서 논의해요!

**Comment by taeguk** [comment]
광민이형 그러면 커밋할때 2,4번도 고쳐서 커밋메세지에 fixed #4 포함해서 커밋해주세요!

**Comment by vyujing** [comment]
오 여긴 이제봤네 ㅋㅋㅋ 아라쓰 ㅋㅋ
