### ISSUE TITLE
Histogram::getKmeansBoundary 코드 리뷰~

### ISSUE THREAD

**Issue by taeguk** [PYO2016/PyoCore#5]
광민이 형이 짜셨던 Histogram::getKmeansBoundary의 코드를 리뷰해봤고, 그 결과 생각난 issue들을 정리해보았습니다.
1. 불필요한 copy constructor이 호출됨. (enhancement)
   https://github.com/PYO2016/PyoCore/blob/6c10a7d0aed47c4fbbc702ee51a9febbc189179a/PyoCore/TableDetection/HistogramManager.cpp#L189
   for (const auto &p : this->extremumList) 로 바꾸는게 좋아보여요.
2. divided by zero 문제 (bug)
   https://github.com/PYO2016/PyoCore/blob/6c10a7d0aed47c4fbbc702ee51a9febbc189179a/PyoCore/TableDetection/HistogramManager.cpp#L231-L232
   if(currentLow > 0) currentLow /= lowCnt; 같은 식으로 바꾸는게 좋을 것 같아요.
3. 광민이형, do-while로 바꾸고 싶으시단거에요?
   https://github.com/PYO2016/PyoCore/blob/6c10a7d0aed47c4fbbc702ee51a9febbc189179a/PyoCore/TableDetection/HistogramManager.cpp#L236-L237
   주석이 do-while로 바꾸고 싶으시단건가요? 만약 그게 맞으면 제가 바꿀수있어요!

**Comment by taeguk** [comment]
2번이 아직 안고쳐진것같아요

**Comment by vyujing** [comment]
뭐지 댓글이 안달렸네 ㅋㅋ

**Comment by vyujing** [comment]
저렇게 되면 if (lowCnt == 0 || upperCnt == 0)에서 걸려서 지금은 return 0이 되게 만들어놨어 ㅋㅋ 저런식으로 클러스터가 1개가 나와버리면 어떻게 처리할지 아직 좀 생각해봐야 할거같아 ㅋㅋ

**Comment by taeguk** [comment]
lowCnt와 upperCnt와 상관없게 while계속 돌도록 함!
만약 클러스터링후 클러스터에 0개가 있는 경우는 그 클러스터의 max or min 값을 0으로 취급하여 boundary 값을 계산함으로서 다른 함수에서 잘 사용할 수 있도록 했음!
