### ISSUE TITLE
Histogram::removeKmeansValues 코드 리뷰

### ISSUE THREAD

**Issue by taeguk** [PYO2016/PyoCore#6]
1. bug
   https://github.com/PYO2016/PyoCore/blob/6c10a7d0aed47c4fbbc702ee51a9febbc189179a/PyoCore/TableDetection/HistogramManager.cpp#L261
   itr->first 가 아니라 this->values[itr->first] 이여야하는거아니에요?? (261줄말고도 이곳저곳에 똑같은 게 있음)
2. 연속되는 상위 클러스터의 극대 찾기부분 (bug)
   https://github.com/PYO2016/PyoCore/blob/6c10a7d0aed47c4fbbc702ee51a9febbc189179a/PyoCore/TableDetection/HistogramManager.cpp#L264
   for (; jtr != end(this->extremumList) && (jtr->second != ExtremumType::TYPE_MAX || this->values[jtr->first] < maxBoundary); ++jtr); 으로 바뀌어야하지 않을까요??
3. 절대 성립할 수 없는 if문 (bug)
   https://github.com/PYO2016/PyoCore/blob/6c10a7d0aed47c4fbbc702ee51a9febbc189179a/PyoCore/TableDetection/HistogramManager.cpp#L282
   282줄의 if문은 절대로 성립할 수 없습니다. 부등호 방향이 minValue > ... 이 아니라 minValue < ... 을 원래 의도 하신 것 같습니다.
   근데 minValue < ... 으로 해도 안됩니다. 같은 값을 가지는 놈이 여러명 있을 수 있기 때문이죠. 따라서 minValue외에도 minIdx를 따로 저장해서 minIdx != ~~~ 이런 식으로 해야할 것 같습니다.

**Comment by vyujing** [comment]
홍ㅋㅋㅋ 이건 모두 수정했어 ㅋㅋ #6으로 올림

**Comment by taeguk** [comment]
ㅋㅋㅋㅋ 이슈 레퍼런스로 인식됐네욬ㅋㅋ close할개용ㅋㅋ
