### ISSUE TITLE
HistogramManager::getTableInfo 코드 리뷰

### ISSUE THREAD

**Issue by taeguk** [PYO2016/PyoCore#7]
1. 지금 코드는 극대, 극소 상관없이 뽑는데 원래 극소만 뽑아야하는거 아녜요?? (지금이 맞는거에요???? )

**Comment by vyujing** [comment]
ㅋㅋ 아닝 극소만 뽑는게 맞아 어제 수정한것들 푸쉬했고 이제 보면서 수정해야겠다 땡큐 ㅋㅋㅋ

**Comment by taeguk** [comment]
lower minimum cluster에서만 뽑는 거로 바꿈!
